#############################################################################
# Makefile for building: Emag.app/Contents/MacOS/Emag
# Generated by qmake (2.01a) (Qt 4.8.0) on: Mon Apr 23 19:12:39 2012
# Project:  Emag.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Emag.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.2
CXX           = g++-4.2
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42 -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = animal.cpp \
		bee.cpp \
		bull.cpp \
		bullet.cpp \
		character.cpp \
		chicken.cpp \
		crow.cpp \
		dog.cpp \
		doghouse.cpp \
		egg.cpp \
		emag.cpp \
		emagwindow.cpp \
		heart.cpp \
		levelone.cpp \
		levels.cpp \
		levelthree.cpp \
		leveltwo.cpp \
		lose.cpp \
		main.cpp \
		pig.cpp \
		start.cpp \
		treasure.cpp \
		win.cpp moc_emag.cpp \
		moc_emagwindow.cpp
OBJECTS       = animal.o \
		bee.o \
		bull.o \
		bullet.o \
		character.o \
		chicken.o \
		crow.o \
		dog.o \
		doghouse.o \
		egg.o \
		emag.o \
		emagwindow.o \
		heart.o \
		levelone.o \
		levels.o \
		levelthree.o \
		leveltwo.o \
		lose.o \
		main.o \
		pig.o \
		start.o \
		treasure.o \
		win.o \
		moc_emag.o \
		moc_emagwindow.o
DIST          = ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		Emag.pro
QMAKE_TARGET  = Emag
DESTDIR       = 
TARGET        = Emag.app/Contents/MacOS/Emag

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Emag.app/Contents/PkgInfo Emag.app/Contents/Resources/empty.lproj Emag.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Emag.app/Contents/MacOS/ || $(MKDIR) Emag.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Emag.pro  ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42/qmake.conf ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Emag.pro
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Emag.pro

Emag.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Emag.app/Contents || $(MKDIR) Emag.app/Contents 
	@$(DEL_FILE) Emag.app/Contents/PkgInfo
	@echo "APPL????" >Emag.app/Contents/PkgInfo
Emag.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Emag.app/Contents/Resources || $(MKDIR) Emag.app/Contents/Resources 
	@touch Emag.app/Contents/Resources/empty.lproj
	
Emag.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Emag.app/Contents || $(MKDIR) Emag.app/Contents 
	@$(DEL_FILE) Emag.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Emag,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++42/Info.plist.app >Emag.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Emag1.0.0 || $(MKDIR) .tmp/Emag1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Emag1.0.0/ && $(COPY_FILE) --parents animal.h bee.h bull.h bullet.h character.h chicken.h crow.h dog.h doghouse.h egg.h emag.h emagwindow.h heart.h levelone.h levels.h levelthree.h leveltwo.h lose.h pig.h start.h treasure.h win.h .tmp/Emag1.0.0/ && $(COPY_FILE) --parents animal.cpp bee.cpp bull.cpp bullet.cpp character.cpp chicken.cpp crow.cpp dog.cpp doghouse.cpp egg.cpp emag.cpp emagwindow.cpp heart.cpp levelone.cpp levels.cpp levelthree.cpp leveltwo.cpp lose.cpp main.cpp pig.cpp start.cpp treasure.cpp win.cpp .tmp/Emag1.0.0/ && (cd `dirname .tmp/Emag1.0.0` && $(TAR) Emag1.0.0.tar Emag1.0.0 && $(COMPRESS) Emag1.0.0.tar) && $(MOVE) `dirname .tmp/Emag1.0.0`/Emag1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Emag1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Emag.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_emag.cpp moc_emagwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_emag.cpp moc_emagwindow.cpp
moc_emag.cpp: character.h \
		treasure.h \
		bull.h \
		animal.h \
		pig.h \
		dog.h \
		doghouse.h \
		bee.h \
		heart.h \
		crow.h \
		bullet.h \
		chicken.h \
		egg.h \
		levels.h \
		levelone.h \
		leveltwo.h \
		levelthree.h \
		lose.h \
		win.h \
		start.h \
		emag.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ emag.h -o moc_emag.cpp

moc_emagwindow.cpp: emag.h \
		character.h \
		treasure.h \
		bull.h \
		animal.h \
		pig.h \
		dog.h \
		doghouse.h \
		bee.h \
		heart.h \
		crow.h \
		bullet.h \
		chicken.h \
		egg.h \
		levels.h \
		levelone.h \
		leveltwo.h \
		levelthree.h \
		lose.h \
		win.h \
		start.h \
		emagwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ emagwindow.h -o moc_emagwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

animal.o: animal.cpp animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animal.o animal.cpp

bee.o: bee.cpp bee.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bee.o bee.cpp

bull.o: bull.cpp bull.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bull.o bull.cpp

bullet.o: bullet.cpp bullet.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

character.o: character.cpp character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o character.cpp

chicken.o: chicken.cpp chicken.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chicken.o chicken.cpp

crow.o: crow.cpp crow.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crow.o crow.cpp

dog.o: dog.cpp dog.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dog.o dog.cpp

doghouse.o: doghouse.cpp doghouse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doghouse.o doghouse.cpp

egg.o: egg.cpp egg.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o egg.o egg.cpp

emag.o: emag.cpp emag.h \
		character.h \
		treasure.h \
		bull.h \
		animal.h \
		pig.h \
		dog.h \
		doghouse.h \
		bee.h \
		heart.h \
		crow.h \
		bullet.h \
		chicken.h \
		egg.h \
		levels.h \
		levelone.h \
		leveltwo.h \
		levelthree.h \
		lose.h \
		win.h \
		start.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emag.o emag.cpp

emagwindow.o: emagwindow.cpp emagwindow.h \
		emag.h \
		character.h \
		treasure.h \
		bull.h \
		animal.h \
		pig.h \
		dog.h \
		doghouse.h \
		bee.h \
		heart.h \
		crow.h \
		bullet.h \
		chicken.h \
		egg.h \
		levels.h \
		levelone.h \
		leveltwo.h \
		levelthree.h \
		lose.h \
		win.h \
		start.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emagwindow.o emagwindow.cpp

heart.o: heart.cpp heart.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o heart.o heart.cpp

levelone.o: levelone.cpp levelone.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o levelone.o levelone.cpp

levels.o: levels.cpp levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o levels.o levels.cpp

levelthree.o: levelthree.cpp levelthree.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o levelthree.o levelthree.cpp

leveltwo.o: leveltwo.cpp leveltwo.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o leveltwo.o leveltwo.cpp

lose.o: lose.cpp lose.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lose.o lose.cpp

main.o: main.cpp emag.h \
		character.h \
		treasure.h \
		bull.h \
		animal.h \
		pig.h \
		dog.h \
		doghouse.h \
		bee.h \
		heart.h \
		crow.h \
		bullet.h \
		chicken.h \
		egg.h \
		levels.h \
		levelone.h \
		leveltwo.h \
		levelthree.h \
		lose.h \
		win.h \
		start.h \
		emagwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pig.o: pig.cpp pig.h \
		animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pig.o pig.cpp

start.o: start.cpp start.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o start.o start.cpp

treasure.o: treasure.cpp treasure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treasure.o treasure.cpp

win.o: win.cpp win.h \
		levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win.o win.cpp

moc_emag.o: moc_emag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_emag.o moc_emag.cpp

moc_emagwindow.o: moc_emagwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_emagwindow.o moc_emagwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

